### PR TITLE
install 2

### PR DESCRIPTION
**Pull request by jburel**
Install ``grunt-cli`` in setup.py

This should install ``grunt-cli`` (not globally) 
The rest should work as before
This means that we should only need to install ``node.js``

To test:

 * uninstall grunt-cli locally
 * delete node_modules directory in omero-figure
 * run python setup.py sdist

### CODE REVIEW

**Comment by jburel** [comment]
@aleksandra-tarkowska reported that she has to run "sudo" in order to have it to work

**Comment by jburel** [comment]
I still found it strange that we need to have it globally installed.

**Comment by atarkowska** [comment]
it is not only me http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo

**Comment by jburel** [comment]
not disputing it, just seems rather strange

**Pull request closed without merging**
